
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrjdczscblulpubcomvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyamRjenNjYmx1bHB1YmNvbXZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjIzNjAsImV4cCI6MjA1ODgzODM2MH0.AGLp_laF4QN0ECsFNB-0_-uVE4cBbKuH1p_cuVR18_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'public',
  },
  global: {
    headers: {
      'x-app-name': 'lovable-hub',
    },
  },
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Helper functions for vote operations
export const incrementVotes = async (
  table: 'projects' | 'project_features' | 'user_votes' | 'waitlist', 
  id: string
) => {
  // First, let's call the 'increment' function to get the new value
  const { data: newValue } = await supabase.rpc('increment', { x: 'votes' });
  
  // Then update the record with the new value
  return supabase
    .from(table)
    .update({ votes: newValue })
    .eq('id', id);
};

export const decrementVotes = async (
  table: 'projects' | 'project_features' | 'user_votes' | 'waitlist', 
  id: string
) => {
  // First, let's call the 'decrement' function to get the new value
  const { data: newValue } = await supabase.rpc('decrement', { x: 'votes' });
  
  // Then update the record with the new value
  return supabase
    .from(table)
    .update({ votes: newValue })
    .eq('id', id);
};
