// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suhdcfzuohldfnojsook.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1aGRjZnp1b2hsZGZub2pzb29rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1NzQ5NjksImV4cCI6MjA5MDE1MDk2OX0.yH5kP8LaMZkiI6mG4zX3XES3odfWcWzNNry-NDXPdIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});