
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrjdczscblulpubcomvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyamRjenNjYmx1bHB1YmNvbXZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjIzNjAsImV4cCI6MjA1ODgzODM2MH0.AGLp_laF4QN0ECsFNB-0_-uVE4cBbKuH1p_cuVR18_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'public',
  },
  global: {
    headers: {
      'x-app-name': 'lovable-hub',
    },
  },
});

// Helper functions for vote operations
export const incrementVotes = (table: "project_features" | "projects" | "user_votes" | "waitlist", id: string) => {
  return supabase
    .from(table)
    .update({ votes: supabase.rpc('increment', { x: 1 }) })
    .eq('id', id);
};

export const decrementVotes = (table: "project_features" | "projects" | "user_votes" | "waitlist", id: string) => {
  return supabase
    .from(table)
    .update({ votes: supabase.rpc('decrement', { x: 1 }) })
    .eq('id', id);
};
